# Generated by Django 4.2.16 on 2024-11-22 14:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('segundo_nombre', models.CharField(blank=True, max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('segundo_apellido', models.CharField(max_length=50)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('N', 'Prefiero No Decirlo'), ('O', 'Otro')], max_length=1)),
                ('telefono', models.CharField(max_length=20)),
                ('admin_pic', models.ImageField(blank=True, upload_to='img/user/')),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Busquedas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad_origen', models.CharField(blank=True, max_length=25)),
                ('ciudad_destino', models.CharField(blank=True, max_length=25)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarritoCompras',
            fields=[
                ('id_carrito', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creada', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizada', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('segundo_nombre', models.CharField(blank=True, max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('segundo_apellido', models.CharField(max_length=50)),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería'), ('PA', 'Pasaporte')], max_length=2)),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('N', 'Prefiero No Decirlo'), ('O', 'Otro')], max_length=1)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=20)),
                ('departamento', models.CharField(max_length=20)),
                ('municipio', models.CharField(max_length=20)),
                ('direccion_facturacion', models.CharField(max_length=50)),
                ('user_pic', models.ImageField(blank=True, upload_to='img/user/')),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComprasReservas',
            fields=[
                ('id_cr', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('COM', 'Comprado'), ('RES', 'Reservado'), ('CAN', 'Cancelado')], max_length=20)),
                ('valor', models.PositiveIntegerField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_viajero', models.PositiveBigIntegerField(blank=True, null=True)),
                ('nombre_viajero', models.CharField(blank=True, max_length=50, null=True)),
                ('segundo_nombre_viajero', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido_viajero', models.CharField(blank=True, max_length=50, null=True)),
                ('segundo_apellido_viajero', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_documento_viajero', models.CharField(blank=True, choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería'), ('PA', 'Pasaporte')], max_length=2, null=True)),
                ('fecha_nacimiento_viajero', models.DateField(blank=True, null=True)),
                ('genero_viajero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('N', 'Prefiero No Decirlo'), ('O', 'Otro')], max_length=1, null=True)),
                ('telefono_viajero', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre_contacto', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono_contacto', models.CharField(blank=True, max_length=20, null=True)),
                ('clase', models.CharField(blank=True, choices=[('E', 'Clase económica'), ('P', 'Primera clase')], max_length=20, null=True)),
                ('precio_modificado', models.PositiveIntegerField(blank=True, null=True)),
                ('tipo_equipaje', models.CharField(blank=True, choices=[('P', 'Equipaje personal'), ('M', 'Equipaje de mano'), ('B', 'Maleta de bodega'), ('PM', 'Personal y Mano'), ('PB', 'Personal y Bodega'), ('MB', 'Mano y Bodega'), ('T', 'Todos')], max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='direccion de correo electrónico')),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Root',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sillas',
            fields=[
                ('id_silla', models.AutoField(primary_key=True, serialize=False)),
                ('ubicacion', models.CharField(max_length=5)),
                ('clase', models.CharField(choices=[('E', 'Clase económica'), ('P', 'Primera clase')], max_length=20)),
                ('estado', models.CharField(choices=[('L', 'Libre'), ('R', 'Reservado'), ('O', 'Ocupado')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tarjetas',
            fields=[
                ('id_tarjeta', models.BigIntegerField(primary_key=True, serialize=False)),
                ('tipo_tarjeta', models.CharField(choices=[('D', 'Débito'), ('C', 'Crédito')], max_length=20)),
                ('vvc', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(9999)])),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_expiracion', models.DateField()),
                ('saldo', models.IntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tiquete',
            fields=[
                ('id_tiquete', models.AutoField(primary_key=True, serialize=False)),
                ('id_viajero', models.PositiveBigIntegerField()),
                ('nombre_viajero', models.CharField(max_length=50)),
                ('segundo_nombre_viajero', models.CharField(blank=True, max_length=50)),
                ('apellido_viajero', models.CharField(max_length=50)),
                ('segundo_apellido_viajero', models.CharField(max_length=50)),
                ('tipo_documento_viajero', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería'), ('PA', 'Pasaporte')], max_length=2)),
                ('fecha_nacimiento_viajero', models.DateField()),
                ('genero_viajero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('N', 'Prefiero No Decirlo'), ('O', 'Otro')], max_length=1)),
                ('telefono_viajero', models.CharField(max_length=20)),
                ('nombre_contacto', models.CharField(max_length=50)),
                ('telefono_contacto', models.CharField(max_length=20)),
                ('clase', models.CharField(choices=[('E', 'Clase económica'), ('P', 'Primera clase')], max_length=20)),
                ('tipo_equipaje', models.CharField(choices=[('P', 'Equipaje personal'), ('M', 'Equipaje de mano'), ('B', 'Maleta de bodega'), ('PM', 'Personal y Mano'), ('PB', 'Personal y Bodega'), ('MB', 'Mano y Bodega'), ('T', 'Todos')], max_length=20)),
                ('verificacion', models.CharField(max_length=50, unique=True)),
                ('verificado', models.BooleanField(default=False)),
                ('email_viajero', models.EmailField(max_length=100, verbose_name='direccion de correo electrónico')),
                ('activo', models.BooleanField(default=True)),
                ('precio', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vuelos',
            fields=[
                ('id_vuelo', models.AutoField(primary_key=True, serialize=False)),
                ('referencia', models.CharField(max_length=20)),
                ('ciudad_origen', models.CharField(max_length=25)),
                ('ciudad_destino', models.CharField(max_length=25)),
                ('precio', models.PositiveIntegerField()),
                ('fecha_salida', models.DateTimeField()),
                ('fecha_llegada', models.DateTimeField(blank=True, null=True)),
                ('duracion', models.FloatField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('N', 'Nacional'), ('I', 'Internacional')], max_length=20)),
                ('estado', models.CharField(choices=[('P', 'Programado'), ('R', 'Realizado')], max_length=20)),
                ('vuelos_pic', models.ImageField(blank=True, upload_to='img/flight/')),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NormalUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.PositiveBigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='direccion de correo electrónico')),
                ('roles', models.PositiveSmallIntegerField(choices=[(1, 'Cliente'), (2, 'Administrador'), (3, 'Root')])),
                ('activo', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='vuelos',
            constraint=models.UniqueConstraint(fields=('ciudad_origen', 'ciudad_destino', 'fecha_salida'), name='unique_flight'),
        ),
        migrations.AddField(
            model_name='tiquete',
            name='id_silla',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='WingCol.sillas'),
        ),
        migrations.AddField(
            model_name='tiquete',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tarjetas',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sillas',
            name='id_vuelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WingCol.vuelos'),
        ),
        migrations.AddField(
            model_name='root',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemcarrito',
            name='id_carrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WingCol.carritocompras'),
        ),
        migrations.AddField(
            model_name='itemcarrito',
            name='id_vuelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WingCol.vuelos'),
        ),
        migrations.AddField(
            model_name='comprasreservas',
            name='id_vuelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WingCol.vuelos'),
        ),
        migrations.AddField(
            model_name='comprasreservas',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WingCol.cliente'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carritocompras',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='busquedas',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WingCol.cliente'),
        ),
        migrations.AddField(
            model_name='administrador',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
