# Generated by Django 4.2.16 on 2024-11-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WingCol', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('N', 'Prefiero No Decirlo'), ('O', 'Otro')], max_length=1),
        ),
        migrations.AddConstraint(
            model_name='vuelos',
            constraint=models.UniqueConstraint(fields=('ciudad_origen', 'ciudad_destino', 'fecha_salida'), name='unique_flight'),
        ),
    ]
