# Generated by Django 4.2.16 on 2024-11-22 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WingCol', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiquete',
            name='email_viajero',
        ),
    ]
