# Generated by Django 4.2.16 on 2024-11-01 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WingCol', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjetas',
            name='nombre',
            field=models.CharField(default='No Name', max_length=50),
            preserve_default=False,
        ),
    ]
