# Generated by Django 4.2.16 on 2024-12-06 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WingCol', '0002_remove_tiquete_email_viajero'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiquete',
            name='email_viajero',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='direccion de correo electrónico'),
        ),
    ]
