# Generated by Django 4.2.16 on 2024-11-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WingCol', '0002_alter_cliente_genero_vuelos_unique_flight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('N', 'Prefiero No Decirlo'), ('O', 'Otro')], max_length=1),
        ),
    ]
