# Generated by Django 4.2.16 on 2024-11-01 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WingCol', '0002_tarjetas_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
    ]
