# Generated by Django 4.2.16 on 2024-11-14 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WingCol', '0003_alter_administrador_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiquete',
            name='apellido',
            field=models.CharField(default='Doe', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tiquete',
            name='fecha_nacimiento',
            field=models.DateField(default='2024-10-14'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tiquete',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('N', 'Prefiero No Decirlo'), ('O', 'Otro')], default='O', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tiquete',
            name='nombre',
            field=models.CharField(default='John', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tiquete',
            name='nombre_contacto',
            field=models.CharField(default='John', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tiquete',
            name='segundo_apellido',
            field=models.CharField(default='Doe', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tiquete',
            name='segundo_nombre',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='tiquete',
            name='telefono',
            field=models.CharField(default='888888888888', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tiquete',
            name='telefono_contacto',
            field=models.CharField(default='33333333333', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tiquete',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería'), ('PA', 'Pasaporte')], default='CC', max_length=2),
            preserve_default=False,
        ),
    ]
