# Generated by Django 4.2.16 on 2024-11-14 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WingCol', '0004_tiquete_apellido_tiquete_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tiquete',
            old_name='apellido',
            new_name='apellido_viajero',
        ),
        migrations.RenameField(
            model_name='tiquete',
            old_name='fecha_nacimiento',
            new_name='fecha_nacimiento_viajero',
        ),
        migrations.RenameField(
            model_name='tiquete',
            old_name='genero',
            new_name='genero_viajero',
        ),
        migrations.RenameField(
            model_name='tiquete',
            old_name='nombre',
            new_name='nombre_viajero',
        ),
        migrations.RenameField(
            model_name='tiquete',
            old_name='segundo_apellido',
            new_name='segundo_apellido_viajero',
        ),
        migrations.RenameField(
            model_name='tiquete',
            old_name='segundo_nombre',
            new_name='segundo_nombre_viajero',
        ),
        migrations.RenameField(
            model_name='tiquete',
            old_name='telefono',
            new_name='telefono_viajero',
        ),
        migrations.RenameField(
            model_name='tiquete',
            old_name='tipo_documento',
            new_name='tipo_documento_viajero',
        ),
    ]
