# Generated by Django 4.2.16 on 2024-11-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WingCol', '0005_rename_apellido_tiquete_apellido_viajero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiquete',
            name='id_viajero',
            field=models.PositiveBigIntegerField(default=11111111111),
            preserve_default=False,
        ),
    ]
