# Generated by Django 4.2.16 on 2024-10-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WingCol', '0005_alter_cliente_pais'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='departamento',
            field=models.CharField(default='Risaralda', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='municipio',
            field=models.CharField(default='Pereira', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vuelos',
            name='referencia',
            field=models.CharField(default='XXX-XXX-DDMMYY', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='busquedas',
            name='activo',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='busquedas',
            name='ciudad_destino',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='busquedas',
            name='ciudad_origen',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='sillas',
            name='id_silla',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vuelos',
            name='id_vuelo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
