# Generated by Django 4.2.16 on 2024-10-04 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WingCol', '0006_cliente_departamento_cliente_municipio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiquete',
            name='id_vuelo',
        ),
        migrations.AddField(
            model_name='tiquete',
            name='id_silla',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='WingCol.sillas'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vuelos',
            name='estado',
            field=models.CharField(choices=[('P', 'Programado'), ('R', 'Realizado')], max_length=20),
        ),
    ]
