# Generated by Django 4.2.16 on 2024-11-20 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WingCol', '0006_tiquete_id_viajero'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarritoCompras',
            fields=[
                ('id_carrito', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creada', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizada', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WingCol.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='tiquete',
            name='precio',
            field=models.PositiveIntegerField(default=500000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tiquete',
            name='verificado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tiquete',
            name='tipo_equipaje',
            field=models.CharField(choices=[('P', 'Equipaje personal'), ('M', 'Equipaje de mano'), ('B', 'Maleta de bodega'), ('PM', 'Personal y Mano'), ('PB', 'Personal y Bodega'), ('MB', 'Mano y Bodega'), ('T', 'Todos')], max_length=20),
        ),
        migrations.CreateModel(
            name='ItemCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('id_carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WingCol.carritocompras')),
                ('id_tiquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WingCol.tiquete')),
            ],
        ),
    ]
