# Generated by Django 4.2.16 on 2024-10-07 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WingCol', '0007_remove_tiquete_id_vuelo_tiquete_id_silla_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='user_pic',
            field=models.ImageField(blank=True, upload_to='img/'),
        ),
    ]
