# Generated by Django 4.2.16 on 2024-11-20 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WingCol', '0007_carritocompras_tiquete_precio_tiquete_verificado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carritocompras',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tiquete',
            name='id_silla',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='WingCol.sillas'),
        ),
        migrations.AlterField(
            model_name='tiquete',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
