# Generated by Django 4.2.16 on 2024-10-07 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WingCol', '0008_administrador_user_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='user_pic',
        ),
        migrations.AddField(
            model_name='cliente',
            name='user_pic',
            field=models.ImageField(blank=True, upload_to='img/'),
        ),
    ]
