# Generated by Django 4.2.16 on 2024-11-20 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WingCol', '0008_alter_carritocompras_user_id_alter_tiquete_id_silla_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcarrito',
            name='id_tiquete',
        ),
        migrations.AddField(
            model_name='itemcarrito',
            name='id_vuelo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='WingCol.vuelos'),
            preserve_default=False,
        ),
    ]
