# Generated by Django 4.2.16 on 2024-11-21 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WingCol', '0009_remove_itemcarrito_id_tiquete_itemcarrito_id_vuelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcarrito',
            name='apellido_viajero',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='itemcarrito',
            name='clase',
            field=models.CharField(blank=True, choices=[('E', 'Clase económica'), ('P', 'Primera clase')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='itemcarrito',
            name='fecha_nacimiento_viajero',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemcarrito',
            name='genero_viajero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('N', 'Prefiero No Decirlo'), ('O', 'Otro')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='itemcarrito',
            name='id_viajero',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemcarrito',
            name='nombre_contacto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='itemcarrito',
            name='nombre_viajero',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='itemcarrito',
            name='segundo_apellido_viajero',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='itemcarrito',
            name='segundo_nombre_viajero',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='itemcarrito',
            name='telefono_contacto',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='itemcarrito',
            name='telefono_viajero',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='itemcarrito',
            name='tipo_documento_viajero',
            field=models.CharField(blank=True, choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería'), ('PA', 'Pasaporte')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='itemcarrito',
            name='tipo_equipaje',
            field=models.CharField(blank=True, choices=[('P', 'Equipaje personal'), ('M', 'Equipaje de mano'), ('B', 'Maleta de bodega'), ('PM', 'Personal y Mano'), ('PB', 'Personal y Bodega'), ('MB', 'Mano y Bodega'), ('T', 'Todos')], max_length=20, null=True),
        ),
    ]
