# Generated by Django 4.2.16 on 2024-10-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WingCol', '0009_remove_administrador_user_pic_cliente_user_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='admin_pic',
            field=models.ImageField(blank=True, upload_to='img/user/'),
        ),
        migrations.AddField(
            model_name='vuelos',
            name='vuelos_pic',
            field=models.ImageField(blank=True, upload_to='img/flight/'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='user_pic',
            field=models.ImageField(blank=True, upload_to='img/user/'),
        ),
    ]
