# Generated by Django 4.2.16 on 2024-10-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WingCol', '0010_administrador_admin_pic_vuelos_vuelos_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprasreservas',
            name='id_cr',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tiquete',
            name='id_tiquete',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
