# Generated by Django 4.2.16 on 2024-11-21 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WingCol', '0010_itemcarrito_apellido_viajero_itemcarrito_clase_and_more'),
    ]

    operations = [
    ]
