# Generated by Django 4.2.16 on 2024-10-25 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WingCol', '0011_alter_comprasreservas_id_cr_alter_tiquete_id_tiquete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busquedas',
            name='activo',
        ),
        migrations.AddField(
            model_name='vuelos',
            name='duracion',
            field=models.FloatField(default=2.5),
            preserve_default=False,
        ),
    ]
