# Generated by Django 4.2.16 on 2024-11-22 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WingCol', '0011_remove_itemcarrito_id_tiquete'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcarrito',
            name='precio_modificado',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
