# Generated by Django 4.2.16 on 2024-10-28 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WingCol', '0012_remove_busquedas_activo_vuelos_duracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vuelos',
            name='duracion',
            field=models.FloatField(blank=True),
        ),
    ]
