# Generated by Django 4.2.16 on 2024-10-30 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WingCol', '0014_alter_vuelos_duracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjetas',
            name='id_tarjeta',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tarjetas',
            name='vvc',
            field=models.PositiveIntegerField(max_length=4),
        ),
    ]
