# Generated by Django 4.2.16 on 2024-10-30 04:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WingCol', '0014_alter_vuelos_duracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjetas',
            name='fecha_expiracion',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='tarjetas',
            name='id_tarjeta',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tarjetas',
            name='saldo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarjetas',
            name='vvc',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
