# Generated by Django 4.2.16 on 2024-10-30 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WingCol', '0015_alter_tarjetas_fecha_expiracion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjetas',
            name='fecha_expiracion',
            field=models.DateField(),
        ),
    ]
