# Generated by Django 4.2.16 on 2024-10-30 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WingCol', '0016_alter_tarjetas_fecha_expiracion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='busquedas',
            old_name='id_cliente',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='comprasreservas',
            old_name='id_cliente',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='tarjetas',
            old_name='id_cliente',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='tiquete',
            old_name='id_cliente',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='vuelos',
            name='fecha_llegada',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
