# Generated by Django 4.2.16 on 2024-10-30 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WingCol', '0017_rename_id_cliente_busquedas_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjetas',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
